### PR TITLE
make auto-complete more comfortable

### PR DESCRIPTION
**Pull request by pittcat**
May it just a draft .I wanna discuss details with you .

### CODE REVIEW

**Comment by liuchengxu** [comment]
Can you elaborate why it's more comfortable?

**Comment by pittcat** [comment]
#### auto-complete layer  
    inoremap <expr> <CR> (pumvisible() ? "\<c-y>\<cr>" : "\<CR>")
    inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
    inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
#### code-snippets
    " Fix tab conflict with YCM
    let g:UltiSnipsExpandTrigger = '<C-e>'
    let g:ulti_expand_or_jump_res = 0
    function! ExpandSnippetOrCarriageReturn()
        let l:snippet = UltiSnips#ExpandSnippetOrJump()
        if g:ulti_expand_or_jump_res > 0
        return l:snippet
        else
        return "\<CR>"
        endif
    endfunction
    inoremap <expr> <CR> pumvisible() ? "\<C-R>=ExpandSnippetOrCarriageReturn()\<CR>" : "\<CR>"
    " } 
if we use apply the above code,it seems like that the code can work well with ycmd ,deoplete,and completor ,but the side effect is that it can make cursor move to next line even if we don't want do that when we pressed enter key.The reason why cursor moved is that we added \<c-y>\<cr> into   auto-complete layer  and return "\<CR>" into code-snippets.

**Comment by pittcat** [comment]
I  refernced ultisnips doc. if we use code as follow ，

        let g:ulti_expand_res = 0
        function ExpandSnippetOrCarriageReturn()
            let snippet = UltiSnips#ExpandSnippet()
            if g:ulti_expand_res > 0
                return snippet
            elseif !empty(glob("$HOME/.vim/plugged/completor.vim"))
                return "\<C-y>"
            elseif !empty(glob("$HOME/.local/share/nvim/plugged/deoplete.nvim")) ||  !empty(glob("$HOME/.vim/plugged/deoplete.nvim"))
                return deoplete#close_popup()
            endif
        endfunction
        inoremap <expr> <CR> pumvisible() ? "<C-R>=ExpandSnippetOrCarriageReturn()<CR>" : "\<CR>"

we can avoid the problem that cursor moved to next line after we pressed enter key .

**Comment by pittcat** [comment]
But unfortunately the above code can't work well with ycmd.soory ，the net is to break.

**Comment by pittcat** [comment]
In addition,we can make tab more  dynamic with the code as follow.


                function TabJumpNext()
                let snippet=UltiSnips#JumpForwards()
                if pumvisible()==0
                    if g:ulti_jump_forwards_res==1
                    return snippet
                    else
                    return "\<tab>"
                    endif
                endif
                endfunction
                inoremap <expr> <tab> pumvisible() ? "<C-n>" : "<C-R>=TabJumpNext()<CR>"

                function STabJumpBack()
                let snippet=UltiSnips#JumpBackwards()
                if pumvisible()==0
                    if g:ulti_jump_backwards_res==1
                    return snippet
                    else
                    return "\<s-tab>"
                    endif
                endif
                endfunction

                inoremap <expr> <s-tab> pumvisible() ? "<C-n>" : "<C-R>=TabJumpNext()<CR>"

                smap <TAB>   <Esc>:call UltiSnips#JumpForwards()<CR>
                smap <S-TAB> <Esc>:call UltiSnips#JumpBackwards()<CR>

One more thing ,we have to update deoplete,because parametors about deoplete had changed a lot.

**Comment by liuchengxu** [comment]
So the `deoplete` layer is not related to the `<CR>` or `<TAB>` conflict in `auto-completion`, `ycmd` and `code-snippets` layer, then I think you should split it out and open up another PR for the deoplete.

Haven't dived into the `auto-completion`, `ycmd` and `code-snippets` changes, but it seemingly doesn't work well in my case.

**Comment by pittcat** [comment]
Ok,I will close the pr and I want to separate the code to different complete layer
                                                 
                    let g:UltiSnipsExpandTrigger = '<C-e>'
                    let g:ulti_expand_or_jump_res = 0
                    function! ExpandSnippetOrCarriageReturn()
                        let l:snippet = UltiSnips#ExpandSnippetOrJump()
                        if g:ulti_expand_or_jump_res > 0
                        return l:snippet
                        else
                        return "\<CR>"
                        endif
                    endfunction
                    inoremap <expr> <CR> pumvisible() ? "\<C-R>=ExpandSnippetOrCarriageReturn()\<CR>" : "\<CR>"

**Comment by liuchengxu** [comment]
The change about deoplete is not complex. You can prepare it first.

**Pull request closed without merging**
