### PR TITLE
Add nvim-install.sh

### PR DESCRIPTION
**Pull request by tleb**
It works for me but it should be tried by other people.

It is just a copy/paste of `install.sh` with the right paths modified. A cleaner option would be to depend on an env variable and modify the paths accordingly.

### CODE REVIEW

**Comment by liuchengxu** [comment]
Thanks, @tleb . But I don't think we have to specifically add another `install.sh` for neovim. Maybe it's better to add an option to the current `install.sh`?

**Comment by liuchengxu** [comment]
I have updated the install.sh in a new branch: https://github.com/liuchengxu/space-vim/tree/installation. Do you mind give it a test?

```vim
# Install space-vim for both Vim and NeoVim
curl -fLo https://raw.githubusercontent.com/liuchengxu/space-vim/installation/install.sh | sh -s -- all

# Only install space-vim for Vim
curl -fLo https://raw.githubusercontent.com/liuchengxu/space-vim/installation/install.sh | sh -s -- vim

# Only install space-vim for NeoVim
curl -fLo https://raw.githubusercontent.com/liuchengxu/space-vim/installation/install.sh | sh -s -- neovim
```

**Comment by tleb** [comment]
The command you gave didn't work (probably a curl argument mistake, I don't know, I don't use curl anymore) but I pulled your branch and the `install.sh` worked without any issue.

**Comment by liuchengxu** [comment]
It's indeed problematic :-(. I believe the following commands should be ok. I have used it to install space-vim in ubuntu successfully.

```vim
# Install space-vim for both Vim and NeoVim
curl -o- -L https://raw.githubusercontent.com/liuchengxu/space-vim/installation/install.sh | sh -s -- all

# Only install space-vim for Vim
curl -o- -L https://raw.githubusercontent.com/liuchengxu/space-vim/installation/install.sh | sh -s -- vim

# Only install space-vim for NeoVim
curl -o- -L https://raw.githubusercontent.com/liuchengxu/space-vim/installation/install.sh | sh -s -- neovim
```

**Pull request closed without merging**
